name: WorkNest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4   # ✅ moved here

flutter:
  uses-material-design: true
  assets:
    - assets/images/WN_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/WN_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/WN_logo.png"
