// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy0mu16s4da64fObmrZqSC4hKSKf-Fx_c',
    appId: '1:1030054945225:web:f6bfda747ea1e6d4820818',
    messagingSenderId: '1030054945225',
    projectId: 'worknest-f0857',
    authDomain: 'worknest-f0857.firebaseapp.com',
    storageBucket: 'worknest-f0857.firebasestorage.app',
    measurementId: 'G-6QSK1FE4Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1lktnt0_ytFfDltdKFQBHsjKUHSbWmR0',
    appId: '1:1030054945225:android:99092e98e9c060b7820818',
    messagingSenderId: '1030054945225',
    projectId: 'worknest-f0857',
    storageBucket: 'worknest-f0857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDEhrQF9TJzguOYz9AXwUrdLJAo7Vt-g',
    appId: '1:1030054945225:ios:61ef965d5885fd01820818',
    messagingSenderId: '1030054945225',
    projectId: 'worknest-f0857',
    storageBucket: 'worknest-f0857.firebasestorage.app',
    iosBundleId: 'com.example.worknestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtDEhrQF9TJzguOYz9AXwUrdLJAo7Vt-g',
    appId: '1:1030054945225:ios:61ef965d5885fd01820818',
    messagingSenderId: '1030054945225',
    projectId: 'worknest-f0857',
    storageBucket: 'worknest-f0857.firebasestorage.app',
    iosBundleId: 'com.example.worknestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy0mu16s4da64fObmrZqSC4hKSKf-Fx_c',
    appId: '1:1030054945225:web:a9b44ce4889830ce820818',
    messagingSenderId: '1030054945225',
    projectId: 'worknest-f0857',
    authDomain: 'worknest-f0857.firebaseapp.com',
    storageBucket: 'worknest-f0857.firebasestorage.app',
    measurementId: 'G-NBB3Q6MTD1',
  );
}
